### ISSUE TITLE
Regarder les mixins avec paramètres

### ISSUE THREAD

**Issue by mathildebuenerd** [Gaistu/ohmyfood#3]
https://github.com/Gaistu/ohmyfood/blob/9323579303ccff62d338fd19e7f0fb80bf0e5e67/scss/style.scss#L55

```scss
@mixin menu($color) {
    background-color: $color;
    box-shadow: 1px 1px 10px $color;
}

@include menu($colour-menu-1);
```

https://sass-lang.com/documentation/at-rules/mixin
